### PR TITLE
local descriptors added

### PR DESCRIPTION
**Pull request by allaffa**
Local descriptors added from the list of PyTorch-Geometric transformations provided in:
https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms

The transformations added are: 

- [Spherical](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.Spherical)
- [PointPairFeatures](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.PointPairFeatures)

### CODE REVIEW

**Review by pzhanggit — COMMENTED** [review]
Is it used in any cases now?

**Comment by allaffa** [comment]
> Is it used in any cases now?

@pzhanggit I will work on it next week. 
However, I thought it might also help you with YQ's data to cope with the small volume of data.

**Review by jychoi-hpc — APPROVED** [review]
It looks ok to me.

**Comment by pzhanggit** [comment]
> 

I see, thanks. Are `SphericalCoordinates` and `PointPairFeatures` supposed to be used simultaneously all the time? If not, could you add an inner `if` to line 72-79?

**Comment by allaffa** [comment]
> I see, thanks. Are `SphericalCoordinates` and `PointPairFeatures` supposed to be used simultaneously all the time? If not, could you add an inner `if` to line 72-79?

@pzhanggit you are right. They can be used independently as well as simultaneously. I will make the changes you asked for.

**Review by pzhanggit — APPROVED** [review]

**Pull request merged**
