### PR TITLE
Alexandria add download bash script

### PR DESCRIPTION
**Pull request by allaffa**

### CODE REVIEW

**Comment by allaffa** [comment]
@ArCho48 @RylieWeaver 
This PR also is a good opportunity for you guys to get better acquainted with data import in HydraGNN.

**Comment by allaffa** [comment]
@jychoi-hpc 
Hi Jong, 
Please make reviewing this as your priority.

**Comment by jychoi-hpc** [comment]
@allaffa I tested on Frontier. Downloading works and train works. Only error I got was on the json file format. I made a fix and created a PR to your branch: https://github.com/allaffa/HydraGNN/pull/20 
If you merge, it will show up here. After merging, I think you can merge. 
Thank you for the PR. It looks great.

**Comment by allaffa** [comment]
> @allaffa I tested on Frontier. Downloading works and train works. Only error I got was on the json file format. I made a fix and created a PR to your branch: [allaffa#20](https://github.com/allaffa/HydraGNN/pull/20) If you merge, it will show up here. After merging, I think you can merge. Thank you for the PR. It looks great.

@jychoi-hpc Thank you for your help!

**Review by jychoi-hpc — APPROVED** [review]
It looks good to me. Thanks for this addition.

**Pull request merged**
