### PR TITLE
update pyg version due to md7 url broken

### PR DESCRIPTION
**Pull request by pzhanggit**

### CODE REVIEW

**Comment by allaffa** [comment]
@pzhanggit 
I will look into it myself as well and see what is the best way to fix this

**Comment by pzhanggit** [comment]
> 
I already fixed it locally. It is caused by file name change in the data website, which, however, is not updated in pytorch geometric. I am trying to figure out a best way to fix it for us and will update you later.

**Review by allaffa — APPROVED** [review]

**Comment by allaffa** [comment]
@pzhanggit 
I see that the PR is in "WIP" mode. What is missing?

**Comment by pzhanggit** [comment]
> 

@allaffa  The current changes work. I am okay to merge.
I was not sure if it is the best way to solve this issue and was trying some fix simple like
```
 class myMD172(torch_geometric.datasets.MD17):
        file_names = {"uracil": "md17_uracil.npz"}
```
, but could not make it work.

**Pull request merged**
