### PR TITLE
Open catalyst 2022

### PR DESCRIPTION
**Pull request by allaffa**
This PR include the following:

1. removes unused import in Open Catalyst 2020 example
2. includes new example for Open Catalyst 2022. I tested the code on Frontier to create AIOS binary files and kick off the training, and it works.

### CODE REVIEW

**Review by jychoi-hpc — APPROVED** [review]
It looks great. Thanks.

**Review by pzhanggit — COMMENTED** [review]
Looks good to me overall.
One comment is that in the current implementation, using the relative node position as an edge feature does not seem to achieve rotation equivariance.

**Comment by allaffa** [comment]
> Looks good to me overall. One comment is that in the current implementation, using the relative node position as an edge feature does not seem to achieve rotation equivariance.

@pzhanggit 
Goo point. In preparation for the GB work, I do not know whether it is best to just use bond length and use equivariance, or renounce to equivariance and add more informative edge features. 
Honestly, I do not even think we will have time to test all the possible combinations of input parameters to see what works best. 
What do you suggest?

**Comment by pzhanggit** [comment]
> > Looks good to me overall. One comment is that in the current implementation, using the relative node position as an edge feature does not seem to achieve rotation equivariance.
> 
> @pzhanggit Goo point. In preparation for the GB work, I do not know whether it is best to just use bond length and use equivariance, or renounce to equivariance and add more informative edge features. Honestly, I do not even think we will have time to test all the possible combinations of input parameters to see what works best. What do you suggest?

Given the short timeline, I suggest we remove the relative position from edge feature to keep the equivariance.

**Comment by allaffa** [comment]
> > > Looks good to me overall. One comment is that in the current implementation, using the relative node position as an edge feature does not seem to achieve rotation equivariance.
> > 
> > 
> > @pzhanggit Goo point. In preparation for the GB work, I do not know whether it is best to just use bond length and use equivariance, or renounce to equivariance and add more informative edge features. Honestly, I do not even think we will have time to test all the possible combinations of input parameters to see what works best. What do you suggest?
> 
> Given the short timeline, I suggest we remove the relative position from edge feature to keep the equivariance.

@pzhanggit 
I just updated both Open Catalyst 2020 and Open Catalyst 2022 examples so that only the distance between nodes is used as edge feature.

**Review by pzhanggit — APPROVED** [review]
Looks good to me.

**Pull request merged**
