### PR TITLE
add node type to configuration.json

### PR DESCRIPTION
**Pull request by pzhanggit**

### CODE REVIEW

**Comment by pzhanggit** [comment]
> Can you add a simple test to stop this from happening again? Just running this file with one epoch in `test_config`

Any thoughts on how to deal with datasets for the suggested run?

**Review by allaffa — APPROVED** [review]

**Comment by streeve** [comment]
> Any thoughts on how to deal with datasets for the suggested run?

Can you just create the minimum number of unit test samples for it to not crash?

**Comment by pzhanggit** [comment]
> > Any thoughts on how to deal with datasets for the suggested run?
> 
> Can you just create the minimum number of unit test samples for it to not crash?

@streeve  Not sure I misunderstand you. Are you suggesting to upload DFT datasets for CI tests?

**Comment by streeve** [comment]
> Not sure I misunderstand you. Are you suggesting to upload DFT datasets for CI tests?

No, just calling the `deterministic_graph_data` with a very small number of samples

**Comment by pzhanggit** [comment]
> > Not sure I misunderstand you. Are you suggesting to upload DFT datasets for CI tests?
> 
> No, just calling the `deterministic_graph_data` with a very small number of samples

Sure, we can do that. The only downside is we need to manually change lots of config dicts due to different datasets. 
The other way (which I think also the better) maybe to simply compare dicts in /.examples/configuration.json and ./tests/inputs/ci_multihead.json and make sure all necessary dicts are there. What do you think?

**Comment by streeve** [comment]
> simply compare dicts in /.examples/configuration.json and ./tests/inputs/ci_multihead.json and make sure all necessary dicts are there. What do you think?

Good point - your idea is better. Can you replace the current minimal `test_config` with that

**Review by streeve — APPROVED** [review]

**Comment by streeve** [comment]
Will add test in a separate PR

**Pull request merged**
