### PR TITLE
Adding PAINNStack

### PR DESCRIPTION
**Pull request by RylieWeaver**
The following is an implementation of the 'Polarizable Atom Interaction Neural Network' (PAINN) model. 

(ArXiV Link](https://arxiv.org/abs/2102.03150)).

This is an **equivariant** message-passing stack.

### CODE REVIEW

**Comment by RylieWeaver** [comment]
Do not approve this yet if it passes the tests. I'm currently commenting out large blocks to identify the cause of the error.

**Comment by RylieWeaver** [comment]
@allaffa @jychoi-hpc @pzhanggit 

Could one of you request to have the tests re-run here? I believe I've made a change to fix an error.

**Comment by pzhanggit** [comment]
> @allaffa @jychoi-hpc @pzhanggit
> 
> Could one of you request to have the tests re-run here? I believe I've made a change to fix an error.

Just re-ran it. It seems there is some format issue

**Comment by RylieWeaver** [comment]
@pzhanggit @allaffa I believe its passed all checks now. Could you review?

**Review by allaffa — APPROVED** [review]

**Comment by allaffa** [comment]
@RylieWeaver 
This PR has conflicts with the main branch and cannot be merged automatically. 
Please solve the conflicts.

**Comment by RylieWeaver** [comment]
@allaffa 

The merge conflicts are fixed. More will pop up when MACE or this one is merged, but that can be fixed quick.

**Pull request merged**
